<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.89" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
      <PackageReference Include="Mjaskiewicz.RadioBrowser" Version="2.0.1" />
    </ItemGroup>

</Project>
